# Each page blueprint must have a title, the title may be different from the file name
title: Projekt

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 🖼

# Page status can be limited, here to `draft` and `listed`.
# More about page status: https://getkirby.com/docs/reference/panel/blueprints/page#statuses
status:
  draft: true
  listed: true

# Define the form layout with two columns
# Columns are optional but help structure the form layout
# The first column defines an files section, the second a set of fields
# More about different types of sections: https://getkirby.com/docs/reference/panel/sections
# More about columns: https://getkirby.com/docs/guide/blueprints/layout#defining-columns

columns:
  - width: 2/3
    # The first column contains a set of fields to store
    # information about the album.
    #
    # List of all available field types:
    # https://getkirby.com/docs/reference/panel/fields
    fields:
      # If you need the same field in multiple locations, you can define them once and reuse whereever needed.
      # Here we use a files field defined in `/site/blueprints/field/cover.yml`
      cover: fields/cover
      headline:
        type: text
        label: Titel
        placeholder: "{{ page.title }}"
        help: Leer lassen, um den Titel als Anriss zu verwenden
      subheadline:
        label: Subtitel
        type: text
      project_status:
        type: select
        label: Projektzustand
        options:
          - in Planung
          - in Vorbereitung
          - aktiv
          - in Auswertung
          - abgeschlossen
      text:
        type: blocks
        fieldsets:
          - gallery
          - heading
          - image
          - video
          - text
          - box
          - faq
          - card
          - testimonial
          - cta


      team:
        type: pages
        label: Team
        template: member
        templates: member
        query: site.find("team")


  - width: 1/3
    sections:
     entries:
       type: pages
       label: Projektschritte
       layout: table
       columns:
         title: true
         project_start_date:
           label: Startdatum
           default: today
         project_start_time:
           label: Startzeit
       templates:
         - project_step
       empty: Noch keine Projektschritte angelegt
       sortBy: project_start_date asc
 
          