# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# add different tabs to clean up the site panel
tabs:
  pages:
    label: Seiten
    icon: page
    sections:
      # The `pages` pages section shows other main pages of the site
      # Using the `templates` option, we limit which types of pages are shown
      # Using the `create` option, we limit the type of page that can be created when a new page is created
      # Note that the `sandbox` page and the `error` page that also exist in the content folder but use different blueprints thus do not show up in the list
      # Since the error page's blueprint is set to `read: false`, it wouldn't show up here even if you added the error blueprint to the templates list
      pages:
        type: pages
        create:
          - default
          - projects
          - blog
          - newsletters
          - team
  newsletter:
    label: Newsletter
    icon: edit
    fields:
      newsletterTeaserHeadline:
        type: text
        label: Teaser Headline
      newsletterTeaserSubheadline:
        type: text
        label: Teaser Subheadline
      newsletterTeaserText:
        type: text
        label: Teaser Text
      newsletterTeaserButtonText:
        type: text
        label: Teaser Button Text
      sections:
        type: pages
        label: Newsletter Seiten
        template: newsletter
  navigation:
    label: Navigation
    icon: bars
    fields:
      navigation:
        type: pages
        label: Navigation
  team:
    label: Team & Partners
    icon: User
    sections:
      staff:
        extends: sections/roles
        query: site.find("team").children.listed().filterBy('teams', 'staff', ',')
        label: Hauptamt
      volunteers:
        extends: sections/roles
        query: site.find("team").children.listed().filterBy('teams', 'volunteer', ',')
        label: Ehrenamt
      partners:
        extends: sections/roles
        query: site.find("team").children.listed().filterBy('teams', 'partner', ',')
        label: Partner
      issuers:
        extends: sections/roles
        query: site.find("team").children.listed().filterBy('teams', 'issuer', ',')
        label: Auftraggeber
  tagebuch:
    label: Tagebuch
    icon: book-open
    sections: 
      published:
        extends: sections/notes
        query: site.find("notes").children.published()
        label: Veröffentlichte Einträge
      drafts:
        extends: sections/notes
        query: site.find("notes").children.drafts()
        label: Entwürfe
  footer:
    label: Footer
    icon: angle-down
    fields:
      social:
        type: structure
        label: Links
        fields:
          link: 
            type: url
            required: true
          title: 
            type: text
      general:
        type: pages
        label: Generelle Seiten
        
    
